### ISSUE TITLE
Post of Update post can't be donne automatically

### ISSUE THREAD

**Issue by JustineBABY** [bitcero/mywords#13]
Hello,

I have this problem, I don't khow if it happen only in my Xoops... When I want to post an article and click on publish (or want to update an article, and click on Update post), I have alway this black screen (and still fix in black screen as pic below). It don't go to be donne automatically, I have alway to press on Refresh of my blowser (firefox or chrome) to have this message: "Post published sucesfully" or "Post updated sucesfully".

You can see in the pic:

![post-or-update-post-can-not-donne-automatically](https://cloud.githubusercontent.com/assets/16358737/15671258/4ca2baae-272a-11e6-82d3-67b213b118c5.jpg)

![my-xoops-config](https://cloud.githubusercontent.com/assets/16358737/15671260/50195242-272a-11e6-8f98-ff8412d63130.jpg)
Mywords vesion: 2.2.5.4

With the best.

**Comment by JustineBABY** [comment]
Hello again,

My problem still the same. I have to refresh my browser to make sucefful the Publish or Update Post action .

Browser: chrome and firefox;
OS: Windows
This is my new installation, and now update from the 2.2.5.4 version to the 2.2.5.5 version.

With the best.

**Comment by bitcero** [comment]
I was unable to reproduce this error after update. Please try to update rmcommon to version 2.5.7.8. I still investigating the error. If you have an URL where to check the problem please provide me the address (send me an email).

**Comment by JustineBABY** [comment]
How can I have the version 2.5.7.8? Now, I have only the version 2.3.2.8 of RMcommon. I have installed this new installation in local, But if you need, I can do it in my test site, and I'll send you the url link.

With the best.
