### ISSUE TITLE
Search Captcha Module for MyWords or such an option

### ISSUE THREAD

**Issue by ghost** [bitcero/mywords#18]
Hello developers,

I want to address a very important issue and indeed how can I activate at MyWords Captcha. A Captcha option there is unfortunately not and I have tons of manual spam in MyWords blog.

But you can be a useful Captcha solution that works for MyWords?

I KeyCaptcha installed, but unfortunately it does not apply to the MyWords modules. Thus every spambot do anything he wants.

Thanks in advance.

**Comment by bitcero** [comment]
I'm preparing a new plugin to use **[reCaptcha](https://github.com/bitcero/recaptcha/)** service with Common Utilities modules and Xoops.

This plugin requires the latest version of Common Utilities, but I'm working in some fixes over rmcommon. If you wish to try you can download the **[Helium branch](https://github.com/bitcero/rmcommon/archive/helium.zip)** of rmcommon.

**Comment by bitcero** [comment]
Google reCaptcha is ready for Common Utilities modules.
