### ISSUE TITLE
"Select User" can't be selected

### ISSUE THREAD

**Issue by JustineBABY** [bitcero/mywords#3]
Hello again,

First, Thanks for your great works.

This is (may be) another bug. I'm not sure if the probleme come from RMcommon or Mywords, but it happen when I do update all the modules yesterday. I try to post some article writed by another users registred, and I try also to select that user as before, but it's not done. It still display everytime: "Sorry, you are not allowed to view this page" (I'm webmaster, so I hava all the right normaly).

You can see in the pic:

![mywords-post-user-01](https://cloud.githubusercontent.com/assets/16358737/12159396/27dfc08c-b4e2-11e5-9b67-9345e30703f0.jpg)

This is my new xoops config:

Xoops: 2.5.7.2
PHP: 5.5.30
Mysql: 5.1.73
RMcommon: 2.3.1.3
Mywords: 2.2.4.9

Best regards
JBB

**Comment by bitcero** [comment]
Ok... confirmed... fixing...

**Comment by JustineBABY** [comment]
I Think that the **"Sorry, you are not allowed to view this page"** notification is come from the file **/modules/rmcommon/ajax/users.php** on line 20 and 40.

JBB

**Comment by JustineBABY** [comment]
Great job, Eduardo. 
It work as well now, thanks. I'll comeback with another bug.

JBB
