### ISSUE TITLE
Where to get the valid .htaccess file for MyWords

### ISSUE THREAD

**Issue by ghost** [bitcero/mywords#7]
Hello Developers,

I would like to SEO-friendly URLs have at the module MyWords but nowhere find a .htaccess file. Can you help me with that? 

When enabled in the Module Options SEO-friendly URLs, no .htaccess is generated and I have in the root directory of my Xoops installation.

Thanks in advance and I am waiting for your answer.

**Comment by bitcero** [comment]
Hello @AlexL777 ...

MyWords uses the htaccess file in root of your XOOPS installation. If your htaccess file could not be updated automatically, you can add the code manually (the module provides you the code).

**Comment by ghost** [comment]
Can you give me perhaps here in Issue show how this rewrite code looks. It must indeed be right for MyWords Categories and Tags.

It is still new for me and I do not know which rewrite rules for MyWords apply.

Thank you!

**Comment by bitcero** [comment]
Remember to enable the option **"Enable URL rewriting"** from Common Utilities. After that you need to set, in MyWords, the option **"Links Format"** to _Based on date and name_ in order to get short URL working.

The htaccess code for MyWords must look similar to this:

```
RewriteRule ^blog/?(.*)$ modules/mywords/index.php [L]
```
